# Generated by Django 3.2.7 on 2021-11-17 18:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='datte',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
