# Generated by Django 3.2.7 on 2021-10-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id_activity', models.AutoField(primary_key=True, serialize=False)),
                ('name_activity', models.CharField(max_length=30)),
                ('unit', models.SmallIntegerField()),
            ],
        ),
    ]
