# Generated by Django 3.2.7 on 2021-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='shortname_activity',
            field=models.CharField(default='OOO', max_length=3),
        ),
    ]
