# Generated by Django 3.2.7 on 2021-11-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_activity_shortname_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='color',
            field=models.CharField(default='white', max_length=20),
        ),
    ]
